version: '3'
services:
  prayer-times-v2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000 
      - 49153:49153
    stdin_open: true
    tty: true
    environment:
      - WDS_SOCKET_PORT=0
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - /app/.next
